var Nette;
(function(i){var j=function(){function b(a){this.length=0;if("string"===typeof a)a=this._find(document,a);else if(!a||a.nodeType||void 0===a.length||a===window)a=[a];for(var h=0,b=a.length;h<b;h++)a[h]&&(this[this.length++]=a[h])}b.factory=function(a){return new b(a)};b.prototype.find=function(a){return new b(this._find(this[0],a))};b.prototype._find=function(a,b){if(!a||!b)return[];if(document.querySelectorAll)return a.querySelectorAll(b);if("#"===b.charAt(0))return[document.getElementById(b.substring(1))];var b=
b.split("."),e=a.getElementsByTagName(b[0]||"*");if(b[1]){for(var c=[],g=RegExp("(^|\\s)"+b[1]+"(\\s|$)"),d=0,f=e.length;d<f;d++)g.test(e[d].className)&&c.push(e[d]);return c}return e};b.prototype.dom=function(){return this[0]};b.prototype.each=function(a){for(var b=0;b<this.length&&!(!1===a.apply(this[b]));b++);return this};b.prototype.bind=function(a,b){if(document.addEventListener&&("mouseenter"===a||"mouseleave"===a))var e=b,a="mouseenter"===a?"mouseover":"mouseout",b=function(a){for(var b=a.relatedTarget;b;b=
b.parentNode)if(b===this)return;e.call(this,a)};return this.each(function(){var c=this,g=c.nette?c.nette:c.nette={},g=g.events=g.events||{};if(!g[a]){var d=g[a]=[],f=function(a){a.target||(a.target=a.srcElement);a.preventDefault||(a.preventDefault=function(){a.returnValue=!1});a.stopPropagation||(a.stopPropagation=function(){a.cancelBubble=!0});a.stopImmediatePropagation=function(){this.stopPropagation();b=d.length};for(var b=0;b<d.length;b++)d[b].call(c,a)};document.addEventListener?c.addEventListener(a,
f,!1):document.attachEvent&&c.attachEvent("on"+a,f)}g[a].push(b)})};b.prototype.addClass=function(a){return this.each(function(){this.className=this.className.replace(/^|\s+|$/g," ").replace(" "+a+" "," ")+" "+a})};b.prototype.removeClass=function(a){return this.each(function(){this.className=this.className.replace(/^|\s+|$/g," ").replace(" "+a+" "," ")})};b.prototype.hasClass=function(a){return this[0]&&-1<this[0].className.replace(/^|\s+|$/g," ").indexOf(" "+a+" ")};b.displays={};b.prototype.show=
function(){return this.each(function(){var a=this.tagName;b.displays[a]||(b.displays[a]=(new b(document.body.appendChild(document.createElement(a)))).css("display"));this.style.display=b.displays[a]})};b.prototype.hide=function(){return this.each(function(){this.style.display="none"})};b.prototype.css=function(a){if(this[0]&&this[0].currentStyle)return this[0].currentStyle[a];if(this[0]&&window.getComputedStyle)return document.defaultView.getComputedStyle(this[0],null).getPropertyValue(a)};b.prototype.data=
function(){if(this[0])return this[0].nette?this[0].nette:this[0].nette={}};b.prototype.val=function(){var a=this[0];if(a)if(a.nodeName){if("select"===a.nodeName.toLowerCase()){var b=a.selectedIndex,e=a.options;if(0>b)return null;if("select-one"===a.type)return e[b].value;b=0;a=[];for(c=e.length;b<c;b++)e[b].selected&&a.push(e[b].value);return a}if("checkbox"===a.type)return a.checked;if(a.value)return a.value.replace(/^\s+|\s+$/g,"")}else{for(var b=0,c=a.length;b<c;b++)if(this[b].checked)return this[b].value;
return null}};b.prototype.trav=function(a,h,e){for(h=h.split(".");a&&!(1===a.nodeType&&(!h[0]||a.tagName.toLowerCase()===h[0])&&(!h[1]||(new b(a)).hasClass(h[1])));)a=a[e];return new b(a||[])};b.prototype.closest=function(a){return this.trav(this[0],a,"parentNode")};b.prototype.prev=function(a){return this.trav(this[0]&&this[0].previousSibling,a,"previousSibling")};b.prototype.next=function(a){return this.trav(this[0]&&this[0].nextSibling,a,"nextSibling")};b.prototype.offset=function(a){if(a)return this.each(function(){for(var b=
this,g=-a.left||0,d=-a.top||0;b=b.offsetParent;)g+=b.offsetLeft,d+=b.offsetTop;this.style.left=-g+"px";this.style.top=-d+"px"});if(this[0]){for(var b=this[0],e={left:b.offsetLeft,top:b.offsetTop};b=b.offsetParent;)e.left+=b.offsetLeft,e.top+=b.offsetTop;return e}};b.prototype.position=function(a){if(a)return this.each(function(){this.nette&&this.nette.onmove&&this.nette.onmove.call(this,a);for(var b in a)this.style[b]=a[b]+"px"});if(this[0])return{left:this[0].offsetLeft,top:this[0].offsetTop,right:this[0].style.right?
parseInt(this[0].style.right,10):0,bottom:this[0].style.bottom?parseInt(this[0].style.bottom,10):0,width:this[0].offsetWidth,height:this[0].offsetHeight}};b.dragging=!1;b.prototype.draggable=function(a){var h=this[0],e=document.documentElement,c,a=a||{};(a.handle?new b(a.handle):this).bind("mousedown",function(g){var d=new b(a.handle?h:this);g.preventDefault();g.stopPropagation();if(b.dragging)return e.onmouseup(g);var f=d.position(),k=a.rightEdge?f.right+g.clientX:f.left-g.clientX,l=a.bottomEdge?
f.bottom+g.clientY:f.top-g.clientY;b.dragging=!0;c=!1;e.onmousemove=function(b){b=b||event;c||(a.draggedClass&&d.addClass(a.draggedClass),a.start&&a.start(b,d),c=!0);var g={};g[a.rightEdge?"right":"left"]=a.rightEdge?k-b.clientX:b.clientX+k;g[a.bottomEdge?"bottom":"top"]=a.bottomEdge?l-b.clientY:b.clientY+l;d.position(g);return!1};e.onmouseup=function(g){c&&(a.draggedClass&&d.removeClass(a.draggedClass),a.stop&&a.stop(g||event,d));b.dragging=e.onmousemove=e.onmouseup=null;return!1}}).bind("click",
function(a){c&&a.stopImmediatePropagation()});return this};return b}();i.Query=j})(Nette||(Nette={}));var __extends=this.__extends||function(i,j){function b(){this.constructor=i}b.prototype=j.prototype;i.prototype=new b};
(function(i){(function(j){var b=i.Query.factory,a=function(a){function c(b){a.call(this,"#nette-debug-panel-"+b.replace("nette-debug-panel-",""))}__extends(c,a);c.PEEK="nette-mode-peek";c.FLOAT="nette-mode-float";c.WINDOW="nette-mode-window";c.FOCUSED="nette-focused";c.zIndex=2E4;c.factory=function(a){return new c(a)};c.toggle=function(a){var c=a.rel,c="#"===c.charAt(0)?b(c):b(a)["prev"===c?"prev":"next"](c.substring(4));"none"===c.css("display")?(c.show(),a.innerHTML=a.innerHTML.replace("\u25ba",
"\u25bc")):(c.hide(),a.innerHTML=a.innerHTML.replace("\u25bc","\u25ba"))};c.prototype.reposition=function(){this.hasClass(c.WINDOW)?window.resizeBy(document.documentElement.scrollWidth-document.documentElement.clientWidth,document.documentElement.scrollHeight-document.documentElement.clientHeight):(this.position({right:this.position().right,bottom:this.position().bottom}),this.position().width&&(document.cookie=this.dom().id+"="+this.position().right+":"+this.position().bottom+"; path=/"))};c.prototype.focus=
function(){this.hasClass(c.WINDOW)?this.data().win.focus():(clearTimeout(this.data().blurTimeout),this.addClass(c.FOCUSED).show(),this[0].style.zIndex=c.zIndex++)};c.prototype.blur=function(){this.removeClass(c.FOCUSED);if(this.hasClass(c.PEEK)){var a=this;this.data().blurTimeout=setTimeout(function(){a.hide()},50)}};c.prototype.toFloat=function(){this.removeClass(c.WINDOW).removeClass(c.PEEK).addClass(c.FLOAT).show().reposition();return this};c.prototype.toPeek=function(){this.removeClass(c.WINDOW).removeClass(c.FLOAT).addClass(c.PEEK).hide();
document.cookie=this.dom().id+"=; path=/"};c.prototype.toWindow=function(){var a=this,d,f;f=this.offset();var e=this.dom().id;f.left+="number"===typeof window.screenLeft?window.screenLeft:window.screenX+10;f.top+="number"===typeof window.screenTop?window.screenTop:window.screenY+50;if(d=window.open("",e.replace(/-/g,"_"),"left="+f.left+",top="+f.top+",width="+f.width+",height="+(f.height+15)+",resizable=yes,scrollbars=yes"))f=d.document,f.write('<!DOCTYPE html><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style>'+
b("#nette-debug-style").dom().innerHTML+"</style><script>"+b("#nette-debug-script").dom().innerHTML+'<\/script><body id="nette-debug">'),f.body.innerHTML='<div class="nette-panel nette-mode-window" id="'+e+'">'+this.dom().innerHTML+"</div>",d.Nette.Debug.Panel.factory(e).initToggler().reposition(),f.title=a.find("h1").dom().innerHTML,b([d]).bind("unload",function(){a.toPeek();d.close()}),b(f).bind("keyup",function(a){27===a.keyCode&&!a.shiftKey&&!a.altKey&&!a.ctrlKey&&!a.metaKey&&d.close()}),document.cookie=
e+"=window; path=/",this.hide().removeClass(c.FLOAT).removeClass(c.PEEK).addClass(c.WINDOW).data().win=d};c.prototype.init=function(){var a=this,d;a.data().onmove=function(a){var b=document,c=window.innerWidth||b.documentElement.clientWidth||b.body.clientWidth,b=window.innerHeight||b.documentElement.clientHeight||b.body.clientHeight;a.right=Math.min(Math.max(a.right,-0.2*this.offsetWidth),c-0.8*this.offsetWidth);a.bottom=Math.min(Math.max(a.bottom,-0.2*this.offsetHeight),b-this.offsetHeight)};b(window).bind("resize",
function(){a.reposition()});a.draggable({rightEdge:!0,bottomEdge:!0,handle:a.find("h1"),stop:function(){a.toFloat()}}).bind("mouseenter",function(){a.focus()}).bind("mouseleave",function(){a.blur()});this.initToggler();a.find(".nette-icons").find("a").bind("click",function(b){"close"===this.rel?a.toPeek():a.toWindow();b.preventDefault()});(d=document.cookie.match(RegExp(a.dom().id+"=(window|(-?[0-9]+):(-?[0-9]+))")))?d[2]?a.toFloat().position({right:d[2],bottom:d[3]}):a.toWindow():a.addClass(c.PEEK)};
c.prototype.initToggler=function(){var a=this;this.bind("click",function(d){var f=b(d.target).closest("a").dom();f&&f.rel&&(c.toggle(f),d.preventDefault(),a.reposition())});return this};return c}(i.Query);j.Panel=a;var h=function(e){function c(){e.call(this,"#nette-debug-bar")}__extends(c,e);c.prototype.init=function(){var c=this,d;c.data().onmove=function(a){var b=document,c=window.innerWidth||b.documentElement.clientWidth||b.body.clientWidth,b=window.innerHeight||b.documentElement.clientHeight||
b.body.clientHeight;a.right=Math.min(Math.max(a.right,0),c-this.offsetWidth);a.bottom=Math.min(Math.max(a.bottom,0),b-this.offsetHeight)};b(window).bind("resize",function(){c.position({right:c.position().right,bottom:c.position().bottom})});c.draggable({rightEdge:!0,bottomEdge:!0,draggedClass:"nette-dragged",stop:function(){document.cookie=c.dom().id+"="+c.position().right+":"+c.position().bottom+"; path=/"}});c.find("a").bind("click",function(c){if("close"===this.rel)b("#nette-debug").hide(),window.opera&&
b("body").show();else if(this.rel){var d=a.factory(this.rel);c.shiftKey?d.toFloat().toWindow():d.hasClass(a.FLOAT)?d.toPeek():d.toFloat().position({right:d.position().right+Math.round(100*Math.random())+20,bottom:d.position().bottom+Math.round(100*Math.random())+20}).reposition()}c.preventDefault()}).bind("mouseenter",function(){if(this.rel&&!("close"===this.rel||c.hasClass("nette-dragged"))){var d=a.factory(this.rel);d.focus();d.hasClass(a.PEEK)&&d.position({right:d.position().right-b(this).offset().left+
d.position().width-b(this).offset().width-4+d.offset().left,bottom:d.position().bottom-b(this).closest("div").offset().top+d.position().height+4+d.offset().top})}}).bind("mouseleave",function(){this.rel&&!("close"===this.rel||c.hasClass("nette-dragged"))&&a.factory(this.rel).blur()});(d=document.cookie.match(RegExp(c.dom().id+"=(-?[0-9]+):(-?[0-9]+)")))&&c.position({right:d[1],bottom:d[2]});c.find("a").each(function(){this.rel&&"close"!==this.rel&&a.factory(this.rel).init()})};return c}(i.Query);
j.Bar=h})(i.Debug||(i.Debug={}))})(Nette||(Nette={}));
